### ISSUE TITLE
Offhand with Trinkets Problem

### ISSUE THREAD

**Issue by Sharterra** [Furgl/Infinitory#1]
I can't interact with the Offhand slot when my inventory expands.   With the mod by itself there is no issue, but when I run this mod with anything that adds a Trinkets based slot like Rings of Ascension it pretty much ignores any clicks on the Offhand slot. I can still use what's in the slot if I put something beforehand, but I can't remove or add an object from it which is quite a hassle when I want to switch between a shield and torch.  Not sure how much yah care about mod compatibilities, but Infinitory is pretty much heaven-sent to anyone running a lot of mods that would normally clog up inventory so I'm willing to live with it.

**Comment by Furgl** [comment]
Trinkets compatibility should be fixed in v1.1
