### ISSUE TITLE
New 3x3 Grid messed up Trinket slots again

### ISSUE THREAD

**Issue by Desempregago** [Furgl/Infinitory#10]
![2021-11-03_23 33 11](https://user-images.githubusercontent.com/14002834/140248074-015b43d4-e6f7-40e7-b20a-e5e3306001d5.png)

**Comment by Desempregago** [comment]
...sorry.

**Comment by Furgl** [comment]
![image](https://user-images.githubusercontent.com/16003461/140334019-b1651c9d-8504-4004-bbcf-db19f2841655.png)
What Trinkets mod(s) do you have installed? I'm not seeing that issue with the ones I have that add more slots to the chestplate.

**Comment by Desempregago** [comment]
I'm using Botania and Things

**Comment by Furgl** [comment]
Could you link the mod? I'm not finding it

**Comment by Desempregago** [comment]
https://www.curseforge.com/minecraft/mc-mods/things-fabric

Botania works as intended, I think it's Things that's breaking

**Comment by Furgl** [comment]
Fixed in v1.2.1 - thanks for reporting!
