### ISSUE TITLE
Shift+click dupes any item starting from third inventory row from top to bottom up to 64

### ISSUE THREAD

**Issue by Desempregago** [Furgl/Infinitory#11]
I can dupe any stackable item starting from the third row of slots in the player's inventory up to 64.

https://user-images.githubusercontent.com/14002834/140390476-dde351b0-a9ee-46d7-bd60-15c73e2716dd.mp4

PS: I'm using an earlier version, but I'm sure the dupe still applies in newer versions

**Comment by yoyo3841** [comment]
Can confirm does work in newest version 1.2.1

**Comment by Furgl** [comment]
Should be fixed with v1.2.2
