### ISSUE TITLE
Item duplication when Shift-Click to inventory

### ISSUE THREAD

**Issue by ppblitto** [Furgl/Infinitory#2]
In my last playthrough this happened to all my stackable items

https://user-images.githubusercontent.com/57157437/136385852-b579bd2e-d446-419b-a2f1-959665ffa5fb.mp4

In this video, I used a netherrack stack to exemplify, but it was happening to all of the other stackable item.

Reentering the world or restarting the game won't solve it.

Thank you for the good job. The mod is awsome!

**Comment by Furgl** [comment]
Thank you for reporting this - what mods do you have installed?

**Comment by Furgl** [comment]
This is fixed in v1.1
