### ISSUE TITLE
Items being displayed as other items in my inventory when I exceed its vanilla limit

### ISSUE THREAD

**Issue by SomeRandomGuyWithGlitchesToReport** [Furgl/Infinitory#3]
![2021-10-12_18 17 27](https://user-images.githubusercontent.com/92392725/137000876-6165ceda-9270-45f0-b73f-4de4337184a4.png)
1.17.1 fabric player, my game's heavily modded (+150) and has 2 datapacks (I could list them all but it'd be a mess so I won't if not asked), sorting my inventory with this mod causes a texture swap, as in: I'm actually wearing a full iron armor (and the origins mod adds some to the armor points so no problem there) right now, but whenever I die or carry a lot of items at once or sort them in any order, the iron armor's texture disappears despite me wearing it, and the helmet is  replaced with a random texture. That happens with every other item including offhand and the added slots for mod cosmetics (I think it's the trinkets mod?) and the banner. Also, dropping them drops the actual items, and some slots are visually empty or full when they shouldn't be, emptying my inventory until it's as full as vanilla and leaving my world seems to fix everything, but then I can't use half of the mod because carrying my stuff again will cause the same issue... I'm pretty sure this issue isn't linked to a specific item either, since it occured at some point in 5 different worlds out of 5 I tested with it... some of my inventory related mods are REI (RoughlyEnoughItems), more banner features, trinkets, one that allows infinite villager trading ( it's barely compatible with this since it takes only one vanilla stack of items on the trading slots and splits my unlimited stacks, shift clicking doesn't work either)... God knows how many library type mods I installed, not sure if they're causing anything tho. I'll stop here for now.
Other than that it's a great mod that fits my nomadic playstyle and combined with waystones, thank you, have a nice day / night.

**Comment by Sharterra** [comment]
Yeah, one of the issues with the mod is that slots created by it and other mods for the purposes of equipment like Trinkets and Backslot are merging.  The only real way around it is to turn off slot creation in Infinitory and make do with infinite stacking or use absolutely no other mods that add anything to the inventory screen.  Even extra menus for the inventory GUI have their tooltips merged with the Infinitory ones though that doesn't seem to hamper functionality.

**Comment by Furgl** [comment]
@SomeRandomGuyWithGlitchesToReport's issue sounds like client-server desync. Relogging should fix that when it happens. Infinitory doesn't affect item stack sizes anywhere but the inventory, as that could possibly break things.

@Sharterra what do you mean by "even extra menus for the inventory GUI have their tooltips merged with the Infinitory ones"? Could you send a screenshot of the issue?

**Comment by Sharterra** [comment]
I mean like the Sorting tooltip will literally occupy the same space as other tooltips.  It's own tooltips are fine.  But if I pulled up the menu for PlayerEx mod it turns the tooltips there into an eldritch mess.  The first pic is the buttons in question with the offending tooltips.  And the second pic is the merging it causes.  The third pic is when I hover my cursor anywhere on the right side outside the window and get the offending tooltips.  I made sure to test this in a new modpack profile and not much on it but what I was testing for Infinitory compatibilities.  So I had PlayerEx (Adds a level up RPG menu linked to the Inventory screen) and it's required library, Data Attributes, to test the tooltips issue and Trinkets to test the extra equipment slot interference.

![2021-10-13_17 36 01](https://user-images.githubusercontent.com/40482129/137222105-3d07d1bd-f5bd-4702-8273-f0aab7b118b5.png)

![2021-10-13_17 36 13](https://user-images.githubusercontent.com/40482129/137222389-ae98252f-fbf0-43ce-84f4-fa7aa4b8d91a.png)

![2021-10-13_17 36 26](https://user-images.githubusercontent.com/40482129/137222396-4fa23f48-6a70-458d-9da6-a37778cd3994.png)

**Comment by Furgl** [comment]
Trinkets compatibility and the inventory button tooltips rendering in the wrong places should be fixed in v1.1

I submit a suggestion to BackSlots that will fix the compatibility issues. It is up to them if they want to fix it: https://github.com/Globox1997/BackSlot/issues/34
