### ISSUE TITLE
Trinkets didn't get fixed after latest update (1.1.0)

### ISSUE THREAD

**Issue by Desempregago** [Furgl/Infinitory#5]
https://user-images.githubusercontent.com/14002834/137811467-bd938927-e92e-4e94-93bf-e970b51ea58b.mp4

**Comment by Furgl** [comment]
What mods do you have installed?

**Comment by Desempregago** [comment]
Quite a few.
![image](https://user-images.githubusercontent.com/14002834/137813750-f3724954-bc0d-453c-ba3d-03f096a0557c.png)

**Comment by Furgl** [comment]
This should be fixed in v1.1.1 - thanks for reporting it!
