### ISSUE TITLE
[Suggestion] Expand the Crafting Grid to 3x3

### ISSUE THREAD

**Issue by Desempregago** [Furgl/Infinitory#6]

**Comment by Sharterra** [comment]
Isn't there other mods for that already?  Granted I've had terrible luck with finding one that plays nice with other things I run on 1.17.

**Comment by Desempregago** [comment]
Implementing it in this mod would make it automatically compatible with the infinite inventory slots.

**Comment by Furgl** [comment]
Added in v1.2.0
