### ISSUE TITLE
[Suggestion] Config option to swap the button/scrollbar location (REI compatibility)

### ISSUE THREAD

**Issue by Desempregago** [Furgl/Infinitory#7]
So THIS
![image](https://user-images.githubusercontent.com/14002834/138006430-deab9476-a4e2-4b2c-b01f-fb7dca9b3492.png)
doesn't happen.

**Comment by Furgl** [comment]
The buttons will be moved in a future gui update, but for now you can resize REI in the config: 
![image](https://user-images.githubusercontent.com/16003461/138115198-22df3eac-6113-476a-9d8f-ec9984338a90.png)
