### ISSUE TITLE
[Bug]Game crash with ArrayIndexOutOfBoundsException when inserting items into double chest

### ISSUE THREAD

**Issue by tksonix** [Furgl/Infinitory#9]
Hi, I have been extensively using this mod but I've found a crashing problem.

When there are too many items stored (in my case above 180 item stacks) and some of the item counts goes over 5k, if the user try to move items to a double chest, the game will crash with `java.lang.ArrayIndexOutOfBoundsException: Index 61 out of bounds for length 54`. 

I have tried an clean install (i.e. no other mod except fabric API and infinitory), the crash still occurs.

I've done some troubleshooting, here are the results:
- Single chest does not any issue.
- having only small amount of item stacks in the inventory also does not have any issue.
- having large amount of item stacks in the inventory while each stack has low count having a different behavior: the game does not crash but a "ghost item stack" is "moved" to the chest, and once the player opens another GUI the item "returns" to the player's inventory.
- having both a large amount of item stacks and big items counts on each stack, the game crash instantly after attempting to transfer the item to the double chest.

While the idea of the mod is to get rid of any storage system but I do need chest for redstone automation.

**Comment by Furgl** [comment]
Could you please attach your crash log? And is this with v1.1.2?

**Comment by tksonix** [comment]
Oh I was having v1.1.1. I didn't noticed there was a v1.1.2 on curseforge. Github and modrinth haven't been updated yet.

And the good news is that the issue I'm having is fixed in the v1.1.2.
